server {
    listen 80;
    server_name seudominio.com.br;

    client_max_body_size 6M;     # acima do limite de 5 MB da imagem do rótulo

    location / {
        proxy_pass http://unix:/run/winerate/gunicorn.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }
}
